# Generated by Django 5.0.7 on 2024-07-21 15:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='timee',
            field=models.DateField(default=datetime.datetime(2024, 7, 21, 18, 54, 39, 411182)),
        ),
    ]
