# Generated by Django 5.0.7 on 2024-07-21 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0002_posts_timee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='timee',
            field=models.TimeField(default='2024-07-21 19:05:04.933940'),
        ),
    ]
