# Generated by Django 5.0.7 on 2024-07-21 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0003_alter_posts_timee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='timee',
            field=models.TimeField(default='2024-07-21 19:40:23.817482'),
        ),
    ]
